# Generated by Django 3.2.5 on 2021-07-23 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='sales.order.number')),
                ('created_date', models.DateTimeField(verbose_name='sales.order.created_date')),
            ],
            options={
                'verbose_name': 'sales.order',
                'verbose_name_plural': 'sales.orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='sales.order_item.created_date')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='sales.order_item.product_price')),
                ('amount', models.IntegerField(verbose_name='sales.order_item.amount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order', verbose_name='sales.order_item.order')),
            ],
            options={
                'verbose_name': 'sales.order_item',
                'verbose_name_plural': 'sales.order_items',
            },
        ),
    ]
